### ISSUE TITLE
Unable to decrypt NCA section fw 9x titles

### ISSUE THREAD

**Issue by dezem** [CaitSith2/SwitchSDTool#14]
I got an error with decrypting a fw 9x title.
Latest keys.txt with key_area_key_application_09 is at the root folder of SwitchSDTool.
```
Exception: Unable to decrypt NCA section.
Key Type: Common
Key Name: key_area_key_application_09
Stack Trace:   bei LibHac.Nca.OpenRawSection(Int32 index, Boolean leaveOpen)
   bei LibHac.Nca.OpenSection(Int32 index, Boolean raw, IntegrityCheckLevel integrityCheckLevel, Boolean leaveOpen)
   bei SwitchSDTool.Form1.btnParseNCA_Click(Object sender, EventArgs e) in H:\DevProjects\SwitchSDTool\SwitchSDTool\Form1.cs:Zeile 1568.
```

**Comment by ccfman2004** [comment]
I have a similar issue but with older titles.  The Luigi's Mansion 3 Update won't show.

**Comment by dezem** [comment]
Luigi Mansion requires fw 9.X.
Hactool in SwitchSDTool needs to be updated.

**Comment by Jdbye** [comment]
Can confirm NSPVerify does not seem to work with master_key_09 games either. Please fix.
`[UPD] Final Fantasy VIII Remastered [01008B900DC0A800][v131072].nsp
Exception: "System.ArgumentNullException" Value cannot be null.
Parameter name: input
Stack Trace:    at System.IO.BinaryReader..ctor(Stream input, Encoding encoding, Boolean leaveOpen)
   at libhac.Pfs..ctor(Stream stream)
   at NSPVerify.Program.Main(String[] args) in H:\DevProjects\SwitchSDTool\NSPVerify\Program.cs:line 113`
