### ISSUE TITLE
NSPVerify exception

### ISSUE THREAD

**Issue by Calahan99** [CaitSith2/SwitchSDTool#7]
Hope this is the correct place to post the problems.

When using NSPVerify I often get the same exception:
`Exceptions caused while parsing the following NSP/NSX files:`
`Name [1234567890123456][v65536].nsp`
`Exception: "System.ArgumentNullException" Der Wert darf nicht NULL sein.`
`Parametername: input`
`Stack Trace:    bei System.IO.BinaryReader..ctor(Stream input, Encoding encoding, Boolean leaveOpen)`
`   bei libhac.Pfs..ctor(Stream stream)`
`   bei NSPVerify.Program.Main(String[] args) in H:\DevProjects\SwitchSDTool\NSPVerify\Program.cs:Zeile 113.`

When checking empty files (0 bytes) you get the following message:
`Checking Name.nsp: Der Index und die Anzahl müssen sich auf eine Position im Puffer beziehen.`
`Parametername: bytes`
`   bei System.Text.ASCIIEncoding.GetString(Byte[] bytes, Int32 byteIndex, Int32 byteCount)`
`   bei libhac.Util.ReadAscii(BinaryReader reader, Int32 size)`
`   bei libhac.PfsHeader..ctor(BinaryReader reader)`
`   bei libhac.Pfs..ctor(Stream stream)`
`   bei NSPVerify.Program.Main(String[] args) in H:\DevProjects\SwitchSDTool\NSPVerify\Program.cs:Zeile 88.`

Version 1.01 still shows `Nintendo Switch NSP Verifier v1.00`

If you need an example file, for the "System.ArgumentNullException", I could send it to you.
On your homepage there is a contact mail address.
The first google unhide isn't working anymore (Error 404) but nearly at the bottom, there's a second one, which I could try.

Thanks for any help.
All the best,
Calahan

**Comment by Jdbye** [comment]
I got the same type of error.

Checking Iconoclasts [0100BC60099FE000].nsp: Value cannot be null.
Parameter name: input
   at System.IO.BinaryReader..ctor(Stream input, Encoding encoding, Boolean leaveOpen)
   at libhac.Pfs..ctor(Stream stream)
   at NSPVerify.Program.Main(String[] args) in H:\DevProjects\SwitchSDTool\NSPVerify\Program.cs:line 113

Checking Tales of Vesperia Definitive Edition [01002C0008E52000][v0].nsp: Value cannot be null.
Parameter name: input
   at System.IO.BinaryReader..ctor(Stream input, Encoding encoding, Boolean leaveOpen)
   at libhac.Pfs..ctor(Stream stream)
   at NSPVerify.Program.Main(String[] args) in H:\DevProjects\SwitchSDTool\NSPVerify\Program.cs:line 113

Checking Undertale [010080B00AD66000].nsp: Value cannot be null.
Parameter name: input
   at System.IO.BinaryReader..ctor(Stream input, Encoding encoding, Boolean leaveOpen)
   at libhac.Pfs..ctor(Stream stream)
   at NSPVerify.Program.Main(String[] args) in H:\DevProjects\SwitchSDTool\NSPVerify\Program.cs:line 113

Not sure if this is a sign that the nsp is bad, or if this is just a bug. All my other nsps except those 3 tested fine.

**Comment by Jdbye** [comment]
I got the same type of error on 3 files. All the others tested OK, I'm not sure if it's a bug or a sign that the nsp is bad and the program doesn't know how to handle it, but I'm inclined to believe the former since it seems like too big of a coincidence that >10% of my nsps result in the exact same issue.

Exceptions caused while parsing the following NSP/NSX files:
nspgames\Iconoclasts [0100BC60099FE000].nsp
Exception: "System.ArgumentNullException" Value cannot be null.
Parameter name: input
Stack Trace:    at System.IO.BinaryReader..ctor(Stream input, Encoding encoding, Boolean leaveOpen)
   at libhac.Pfs..ctor(Stream stream)
   at NSPVerify.Program.Main(String[] args) in H:\DevProjects\SwitchSDTool\NSPVerify\Program.cs:line 113

nspgames\Tales of Vesperia Definitive Edition [01002C0008E52000][v0].nsp
Exception: "System.ArgumentNullException" Value cannot be null.
Parameter name: input
Stack Trace:    at System.IO.BinaryReader..ctor(Stream input, Encoding encoding, Boolean leaveOpen)
   at libhac.Pfs..ctor(Stream stream)
   at NSPVerify.Program.Main(String[] args) in H:\DevProjects\SwitchSDTool\NSPVerify\Program.cs:line 113

nspgames\Undertale [010080B00AD66000].nsp
Exception: "System.ArgumentNullException" Value cannot be null.
Parameter name: input
Stack Trace:    at System.IO.BinaryReader..ctor(Stream input, Encoding encoding, Boolean leaveOpen)
   at libhac.Pfs..ctor(Stream stream)
   at NSPVerify.Program.Main(String[] args) in H:\DevProjects\SwitchSDTool\NSPVerify\Program.cs:line 113

**Comment by Jdbye** [comment]
Looks like this is caused by not having the needed key in keys.txt. It went away once I added some keys I was missing and now all the nsps verify OK. It's probably a good idea to add a more descriptive error message, letting the user know which key is missing.

@Calahan99 Give that solution a try and see if it works for you as well.

**Comment by Calahan99** [comment]
Jdbye's tip was working for me too. I used "NX Game Info" and found that all exceptions were raised because those nsp files needed the Masterkey 6. I then used Lockpick to export a new key file.
Now all exceptions are gone. Maybe CaitSith2 can catch the exception and give a hint for a missing key in the keys.txt file.
@Jdbye Well done! Thanks!
